#! python3
# -*- encoding: utf-8 -*-
"""Callback handlers for tracking LLM and Tool execution events.

@File   :   callbacks.py
@Created:   2026/06/21 02:02
@Author :   SwordJack
@Contact:   https://github.com/SwordJack/
"""

from typing import Any, Dict, List, Optional

class BaseLLMCallback:
    """Base class for handling events during LLM orchestration.

    Subclass this and pass an instance to `client.ask(..., callbacks=[...])`
    to hook into the lifecycle events (like tool execution) for UI updates
    or tracing.
    """

    def on_tool_start(self, tool_name: str, arguments: Dict[str, Any]) -> None:
        """Fired just before a tool is executed locally.

        Args:
            tool_name: The name of the tool (e.g., 'web_search').
            arguments: The JSON-parsed dictionary of arguments generated by the LLM.
        """
        pass

    def on_tool_end(self, tool_name: str, result: Any) -> None:
        """Fired immediately after a tool finishes execution.

        Args:
            tool_name: The name of the tool.
            result: The raw Python object returned by the tool.
                    For 'web_search', this is typically a `SearchResult` dataclass.
        """
        pass

    def on_error(self, error: Exception) -> None:
        """Fired if an unexpected error occurs during orchestration.

        Args:
            error: The exception instance.
        """
        pass


class CallbackManager:
    """Manages a list of LLM callback handlers and dispatches events safely.

    This ensures that errors raised within user-defined callbacks do not crash
    the main orchestration loop.
    """

    def __init__(self, callbacks: Optional[List[BaseLLMCallback]] = None) -> None:
        self.callbacks = callbacks or []

    def on_tool_start(self, tool_name: str, arguments: Dict[str, Any]) -> None:
        """Propagates the tool start event to all registered handlers."""
        for cb in self.callbacks:
            try:
                cb.on_tool_start(tool_name, arguments)
            except Exception as e:
                self.on_error(e)

    def on_tool_end(self, tool_name: str, result: Any) -> None:
        """Propagates the tool end event to all registered handlers."""
        for cb in self.callbacks:
            try:
                cb.on_tool_end(tool_name, result)
            except Exception as e:
                self.on_error(e)

    def on_error(self, error: Exception) -> None:
        """Propagates error events to callback handlers."""
        for cb in self.callbacks:
            try:
                cb.on_error(error)
            except Exception:
                # Prevent callbacks' error-handling itself from crashing
                pass
