context:
  name: "isobase"
  version: "0.0.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: |
    echo "Building version: ${{ version }}"
    python -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - annotated-types
    - anthropic
    - colorlog
    - httpx
    - openai
    - phonenumbers
    - pillow
    - pydantic
    - pycountry
    - pyyaml
    - regex
    - requests
    - sqlalchemy
    - sqlite
    - tavily-python

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - isobase
      pip_check: true

about:
  homepage: https://github.com/landspark/IsoBase
  repository: https://github.com/landspark/IsoBase
  summary: Isomorphic Base (IsoBase) is a Python automation framework built around a JSON-driven workflow engine with AI/LLM integration.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SwordJack
